global:
  scrape_interval: 10s
  evaluation_interval: 1m

  external_labels:
    monitor: 'kopring-hexa-monitor'

scrape_configs:
  - job_name: 'kopring-hexa'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']